export const countryCode = [
    { "country": "United States", "code": "+1", "flag": "https://flagcdn.com/w320/us.png" },
    { "country": "Canada", "code": "+1", "flag": "https://flagcdn.com/w320/ca.png" },
    { "country": "Russia", "code": "+7", "flag": "https://flagcdn.com/w320/ru.png" },
    { "country": "Kazakhstan", "code": "+7", "flag": "https://flagcdn.com/w320/kz.png" },
    { "country": "Egypt", "code": "+20", "flag": "https://flagcdn.com/w320/eg.png" },
    { "country": "South Africa", "code": "+27", "flag": "https://flagcdn.com/w320/za.png" },
    { "country": "Greece", "code": "+30", "flag": "https://flagcdn.com/w320/gr.png" },
    { "country": "Netherlands", "code": "+31", "flag": "https://flagcdn.com/w320/nl.png" },
    { "country": "Belgium", "code": "+32", "flag": "https://flagcdn.com/w320/be.png" },
    { "country": "France", "code": "+33", "flag": "https://flagcdn.com/w320/fr.png" },
    { "country": "Spain", "code": "+34", "flag": "https://flagcdn.com/w320/es.png" },
    { "country": "Hungary", "code": "+36", "flag": "https://flagcdn.com/w320/hu.png" },
    { "country": "Italy", "code": "+39", "flag": "https://flagcdn.com/w320/it.png" },
    { "country": "Vatican City", "code": "+39", "flag": "https://flagcdn.com/w320/va.png" },
    { "country": "Romania", "code": "+40", "flag": "https://flagcdn.com/w320/ro.png" },
    { "country": "Switzerland", "code": "+41", "flag": "https://flagcdn.com/w320/ch.png" },
    { "country": "Austria", "code": "+43", "flag": "https://flagcdn.com/w320/at.png" },
    { "country": "United Kingdom", "code": "+44", "flag": "https://flagcdn.com/w320/gb.png" },
    { "country": "Denmark", "code": "+45", "flag": "https://flagcdn.com/w320/dk.png" },
    { "country": "Sweden", "code": "+46", "flag": "https://flagcdn.com/w320/se.png" },
    { "country": "Norway", "code": "+47", "flag": "https://flagcdn.com/w320/no.png" },
    { "country": "Poland", "code": "+48", "flag": "https://flagcdn.com/w320/pl.png" },
    { "country": "Germany", "code": "+49", "flag": "https://flagcdn.com/w320/de.png" },
    { "country": "Peru", "code": "+51", "flag": "https://flagcdn.com/w320/pe.png" },
    { "country": "Mexico", "code": "+52", "flag": "https://flagcdn.com/w320/mx.png" },
    { "country": "Cuba", "code": "+53", "flag": "https://flagcdn.com/w320/cu.png" },
    { "country": "Argentina", "code": "+54", "flag": "https://flagcdn.com/w320/ar.png" },
    { "country": "Brazil", "code": "+55", "flag": "https://flagcdn.com/w320/br.png" },
    { "country": "Chile", "code": "+56", "flag": "https://flagcdn.com/w320/cl.png" },
    { "country": "Colombia", "code": "+57", "flag": "https://flagcdn.com/w320/co.png" },
    { "country": "Venezuela", "code": "+58", "flag": "https://flagcdn.com/w320/ve.png" },
    { "country": "Malaysia", "code": "+60", "flag": "https://flagcdn.com/w320/my.png" },
    { "country": "Australia", "code": "+61", "flag": "https://flagcdn.com/w320/au.png" },
    { "country": "Indonesia", "code": "+62", "flag": "https://flagcdn.com/w320/id.png" },
    { "country": "Philippines", "code": "+63", "flag": "https://flagcdn.com/w320/ph.png" },
    { "country": "New Zealand", "code": "+64", "flag": "https://flagcdn.com/w320/nz.png" },
    { "country": "Singapore", "code": "+65", "flag": "https://flagcdn.com/w320/sg.png" },
    { "country": "Thailand", "code": "+66", "flag": "https://flagcdn.com/w320/th.png" },
    { "country": "Japan", "code": "+81", "flag": "https://flagcdn.com/w320/jp.png" },
    { "country": "South Korea", "code": "+82", "flag": "https://flagcdn.com/w320/kr.png" },
    { "country": "Vietnam", "code": "+84", "flag": "https://flagcdn.com/w320/vn.png" },
    { "country": "China", "code": "+86", "flag": "https://flagcdn.com/w320/cn.png" },
    { "country": "Turkey", "code": "+90", "flag": "https://flagcdn.com/w320/tr.png" },
    { "country": "India", "code": "+91", "flag": "https://flagcdn.com/w320/in.png" },
    { "country": "Pakistan", "code": "+92", "flag": "https://flagcdn.com/w320/pk.png" },
    { "country": "Afghanistan", "code": "+93", "flag": "https://flagcdn.com/w320/af.png" },
    { "country": "Sri Lanka", "code": "+94", "flag": "https://flagcdn.com/w320/lk.png" },
    { "country": "Myanmar", "code": "+95", "flag": "https://flagcdn.com/w320/mm.png" },
    { "country": "Iran", "code": "+98", "flag": "https://flagcdn.com/w320/ir.png" },
    { "country": "Algeria", "code": "+213", "flag": "https://flagcdn.com/w320/dz.png" },
    { "country": "Morocco", "code": "+212", "flag": "https://flagcdn.com/w320/ma.png" },
    { "country": "Tunisia", "code": "+216", "flag": "https://flagcdn.com/w320/tn.png" },
    { "country": "Libya", "code": "+218", "flag": "https://flagcdn.com/w320/ly.png" },
    { "country": "Gambia", "code": "+220", "flag": "https://flagcdn.com/w320/gm.png" },
    { "country": "Senegal", "code": "+221", "flag": "https://flagcdn.com/w320/sn.png" },
    { "country": "Mauritania", "code": "+222", "flag": "https://flagcdn.com/w320/mr.png" },
    { "country": "Mali", "code": "+223", "flag": "https://flagcdn.com/w320/ml.png" },
    { "country": "Guinea", "code": "+224", "flag": "https://flagcdn.com/w320/gn.png" },
    { "country": "Ivory Coast", "code": "+225", "flag": "https://flagcdn.com/w320/ci.png" },
    { "country": "Burkina Faso", "code": "+226", "flag": "https://flagcdn.com/w320/bf.png" },
    { "country": "Niger", "code": "+227", "flag": "https://flagcdn.com/w320/ne.png" },
    { "country": "Togo", "code": "+228", "flag": "https://flagcdn.com/w320/tg.png" },
    { "country": "Benin", "code": "+229", "flag": "https://flagcdn.com/w320/bj.png" },
    { "country": "Mauritius", "code": "+230", "flag": "https://flagcdn.com/w320/mu.png" },
    { "country": "Liberia", "code": "+231", "flag": "https://flagcdn.com/w320/lr.png" },
    { "country": "Sierra Leone", "code": "+232", "flag": "https://flagcdn.com/w320/sl.png" },
    { "country": "Ghana", "code": "+233", "flag": "https://flagcdn.com/w320/gh.png" },
    { "country": "Nigeria", "code": "+234", "flag": "https://flagcdn.com/w320/ng.png" },
    { "country": "Chad", "code": "+235", "flag": "https://flagcdn.com/w320/td.png" },
    { "country": "Central African Republic", "code": "+236", "flag": "https://flagcdn.com/w320/cf.png" },
    { "country": "Cameroon", "code": "+237", "flag": "https://flagcdn.com/w320/cm.png" },
    { "country": "Cape Verde", "code": "+238", "flag": "https://flagcdn.com/w320/cv.png" },
    { "country": "São Tomé and Príncipe", "code": "+239", "flag": "https://flagcdn.com/w320/st.png" },
    { "country": "Equatorial Guinea", "code": "+240", "flag": "https://flagcdn.com/w320/gq.png" },
    { "country": "Gabon", "code": "+241", "flag": "https://flagcdn.com/w320/ga.png" },
    { "country": "Republic of the Congo", "code": "+242", "flag": "https://flagcdn.com/w320/cg.png" },
    { "country": "Democratic Republic of the Congo", "code": "+243", "flag": "https://flagcdn.com/w320/cd.png" },
    { "country": "Angola", "code": "+244", "flag": "https://flagcdn.com/w320/ao.png" },
    { "country": "Guinea-Bissau", "code": "+245", "flag": "https://flagcdn.com/w320/gw.png" },
    { "country": "British Indian Ocean Territory", "code": "+246", "flag": "https://flagcdn.com/w320/io.png" },
    { "country": "Ascension Island", "code": "+247", "flag": "https://flagcdn.com/w320/ac.png" },
    { "country": "Seychelles", "code": "+248", "flag": "https://flagcdn.com/w320/sc.png" },
    { "country": "Sudan", "code": "+249", "flag": "https://flagcdn.com/w320/sd.png" },
    { "country": "Rwanda", "code": "+250", "flag": "https://flagcdn.com/w320/rw.png" },
    { "country": "Ethiopia", "code": "+251", "flag": "https://flagcdn.com/w320/et.png" },
    { "country": "Somalia", "code": "+252", "flag": "https://flagcdn.com/w320/so.png" },
    { "country": "Djibouti", "code": "+253", "flag": "https://flagcdn.com/w320/dj.png" },
    { "country": "Kenya", "code": "+254", "flag": "https://flagcdn.com/w320/ke.png" },
    { "country": "Tanzania", "code": "+255", "flag": "https://flagcdn.com/w320/tz.png" },
    { "country": "Uganda", "code": "+256", "flag": "https://flagcdn.com/w320/ug.png" },
    { "country": "Burundi", "code": "+257", "flag": "https://flagcdn.com/w320/bi.png" },
    { "country": "Mozambique", "code": "+258", "flag": "https://flagcdn.com/w320/mz.png" },
    { "country": "Zambia", "code": "+260", "flag": "https://flagcdn.com/w320/zm.png" },
    { "country": "Madagascar", "code": "+261", "flag": "https://flagcdn.com/w320/mg.png" },
    { "country": "Réunion", "code": "+262", "flag": "https://flagcdn.com/w320/re.png" },
    { "country": "Zimbabwe", "code": "+263", "flag": "https://flagcdn.com/w320/zw.png" },
    { "country": "Namibia", "code": "+264", "flag": "https://flagcdn.com/w320/na.png" },
    { "country": "Malawi", "code": "+265", "flag": "https://flagcdn.com/w320/mw.png" },
    { "country": "Lesotho", "code": "+266", "flag": "https://flagcdn.com/w320/ls.png" },
    { "country": "Botswana", "code": "+267", "flag": "https://flagcdn.com/w320/bw.png" },
    { "country": "Eswatini", "code": "+268", "flag": "https://flagcdn.com/w320/sz.png" },
    { "country": "Comoros", "code": "+269", "flag": "https://flagcdn.com/w320/km.png" },
    { "country": "Saint Helena", "code": "+290", "flag": "https://flagcdn.com/w320/sh.png" },
    { "country": "Eritrea", "code": "+291", "flag": "https://flagcdn.com/w320/er.png" },
    { "country": "Aruba", "code": "+297", "flag": "https://flagcdn.com/w320/aw.png" },
    { "country": "Faroe Islands", "code": "+298", "flag": "https://flagcdn.com/w320/fo.png" },
    { "country": "Greenland", "code": "+299", "flag": "https://flagcdn.com/w320/gl.png" },
    { "country": "Gibraltar", "code": "+350", "flag": "https://flagcdn.com/w320/gi.png" },
    { "country": "Portugal", "code": "+351", "flag": "https://flagcdn.com/w320/pt.png" },
    { "country": "Luxembourg", "code": "+352", "flag": "https://flagcdn.com/w320/lu.png" },
    { "country": "Ireland", "code": "+353", "flag": "https://flagcdn.com/w320/ie.png" },
    { "country": "Iceland", "code": "+354", "flag": "https://flagcdn.com/w320/is.png" },
    { "country": "Albania", "code": "+355", "flag": "https://flagcdn.com/w320/al.png" },
    { "country": "Malta", "code": "+356", "flag": "https://flagcdn.com/w320/mt.png" },
    { "country": "Cyprus", "code": "+357", "flag": "https://flagcdn.com/w320/cy.png" },
    { "country": "Finland", "code": "+358", "flag": "https://flagcdn.com/w320/fi.png" },
    { "country": "Bulgaria", "code": "+359", "flag": "https://flagcdn.com/w320/bg.png" },
    { "country": "Lithuania", "code": "+370", "flag": "https://flagcdn.com/w320/lt.png" },
    { "country": "Latvia", "code": "+371", "flag": "https://flagcdn.com/w320/lv.png" },
    { "country": "Estonia", "code": "+372", "flag": "https://flagcdn.com/w320/ee.png" },
    { "country": "Moldova", "code": "+373", "flag": "https://flagcdn.com/w320/md.png" },
    { "country": "Armenia", "code": "+374", "flag": "https://flagcdn.com/w320/am.png" },
    { "country": "Belarus", "code": "+375", "flag": "https://flagcdn.com/w320/by.png" },
    { "country": "Andorra", "code": "+376", "flag": "https://flagcdn.com/w320/ad.png" },
    { "country": "Monaco", "code": "+377", "flag": "https://flagcdn.com/w320/mc.png" },
    { "country": "San Marino", "code": "+378", "flag": "https://flagcdn.com/w320/sm.png" },
    { "country": "Ukraine", "code": "+380", "flag": "https://flagcdn.com/w320/ua.png" },
    { "country": "Serbia", "code": "+381", "flag": "https://flagcdn.com/w320/rs.png" },
    { "country": "Montenegro", "code": "+382", "flag": "https://flagcdn.com/w320/me.png" },
    { "country": "Kosovo", "code": "+383", "flag": "https://flagcdn.com/w320/xk.png" },
    { "country": "Croatia", "code": "+385", "flag": "https://flagcdn.com/w320/hr.png" },
    { "country": "Slovenia", "code": "+386", "flag": "https://flagcdn.com/w320/si.png" },
    { "country": "Bosnia and Herzegovina", "code": "+387", "flag": "https://flagcdn.com/w320/ba.png" },
    { "country": "North Macedonia", "code": "+389", "flag": "https://flagcdn.com/w320/mk.png" },
    { "country": "Czech Republic", "code": "+420", "flag": "https://flagcdn.com/w320/cz.png" },
    { "country": "Slovakia", "code": "+421", "flag": "https://flagcdn.com/w320/sk.png" },
    { "country": "Liechtenstein", "code": "+423", "flag": "https://flagcdn.com/w320/li.png" },
    { "country": "Falkland Islands", "code": "+500", "flag": "https://flagcdn.com/w320/fk.png" },
    { "country": "Belize", "code": "+501", "flag": "https://flagcdn.com/w320/bz.png" },
    { "country": "Guatemala", "code": "+502", "flag": "https://flagcdn.com/w320/gt.png" },
    { "country": "El Salvador", "code": "+503", "flag": "https://flagcdn.com/w320/sv.png" },
    { "country": "Honduras", "code": "+504", "flag": "https://flagcdn.com/w320/hn.png" },
    { "country": "Nicaragua", "code": "+505", "flag": "https://flagcdn.com/w320/ni.png" },
    { "country": "Costa Rica", "code": "+506", "flag": "https://flagcdn.com/w320/cr.png" },
    { "country": "Panama", "code": "+507", "flag": "https://flagcdn.com/w320/pa.png" },
    { "country": "Saint Pierre and Miquelon", "code": "+508", "flag": "https://flagcdn.com/w320/pm.png" },
    { "country": "Haiti", "code": "+509", "flag": "https://flagcdn.com/w320/ht.png" },
    { "country": "Guadeloupe", "code": "+590", "flag": "https://flagcdn.com/w320/gp.png" },
    { "country": "Bolivia", "code": "+591", "flag": "https://flagcdn.com/w320/bo.png" },
    { "country": "Guyana", "code": "+592", "flag": "https://flagcdn.com/w320/gy.png" },
    { "country": "Ecuador", "code": "+593", "flag": "https://flagcdn.com/w320/ec.png" },
    { "country": "French Guiana", "code": "+594", "flag": "https://flagcdn.com/w320/gf.png" },
    { "country": "Paraguay", "code": "+595", "flag": "https://flagcdn.com/w320/py.png" },
    { "country": "Martinique", "code": "+596", "flag": "https://flagcdn.com/w320/mq.png" },
    { "country": "Suriname", "code": "+597", "flag": "https://flagcdn.com/w320/sr.png" },
    { "country": "Uruguay", "code": "+598", "flag": "https://flagcdn.com/w320/uy.png" },
    { "country": "Curaçao", "code": "+599", "flag": "https://flagcdn.com/w320/cw.png" },
    { "country": "East Timor", "code": "+670", "flag": "https://flagcdn.com/w320/tl.png" },
    { "country": "Antarctica", "code": "+672", "flag": "https://flagcdn.com/w320/aq.png" },
    { "country": "Brunei", "code": "+673", "flag": "https://flagcdn.com/w320/bn.png" },
    { "country": "Nauru", "code": "+674", "flag": "https://flagcdn.com/w320/nr.png" },
    { "country": "Papua New Guinea", "code": "+675", "flag": "https://flagcdn.com/w320/pg.png" },
    { "country": "Tonga", "code": "+676", "flag": "https://flagcdn.com/w320/to.png" },
    { "country": "Solomon Islands", "code": "+677", "flag": "https://flagcdn.com/w320/sb.png" },
    { "country": "Vanuatu", "code": "+678", "flag": "https://flagcdn.com/w320/vu.png" },
    { "country": "Fiji", "code": "+679", "flag": "https://flagcdn.com/w320/fj.png" },
    { "country": "Palau", "code": "+680", "flag": "https://flagcdn.com/w320/pw.png" },
    { "country": "Wallis and Futuna", "code": "+681", "flag": "https://flagcdn.com/w320/wf.png" },
    { "country": "Cook Islands", "code": "+682", "flag": "https://flagcdn.com/w320/ck.png" },
    { "country": "Niue", "code": "+683", "flag": "https://flagcdn.com/w320/nu.png" },
    { "country": "American Samoa", "code": "+684", "flag": "https://flagcdn.com/w320/as.png" },
    { "country": "Samoa", "code": "+685", "flag": "https://flagcdn.com/w320/ws.png" },
    { "country": "Kiribati", "code": "+686", "flag": "https://flagcdn.com/w320/ki.png" },
    { "country": "New Caledonia", "code": "+687", "flag": "https://flagcdn.com/w320/nc.png" },
    { "country": "Tuvalu", "code": "+688", "flag": "https://flagcdn.com/w320/tv.png" },
    { "country": "French Polynesia", "code": "+689", "flag": "https://flagcdn.com/w320/pf.png" },
    { "country": "Tokelau", "code": "+690", "flag": "https://flagcdn.com/w320/tk.png" },
    { "country": "Micronesia", "code": "+691", "flag": "https://flagcdn.com/w320/fm.png" },
    { "country": "Marshall Islands", "code": "+692", "flag": "https://flagcdn.com/w320/mh.png" },
    { "country": "North Korea", "code": "+850", "flag": "https://flagcdn.com/w320/kp.png" },
    { "country": "Hong Kong", "code": "+852", "flag": "https://flagcdn.com/w320/hk.png" },
    { "country": "Macau", "code": "+853", "flag": "https://flagcdn.com/w320/mo.png" },
    { "country": "Cambodia", "code": "+855", "flag": "https://flagcdn.com/w320/kh.png" },
    { "country": "Laos", "code": "+856", "flag": "https://flagcdn.com/w320/la.png" },
    { "country": "Bangladesh", "code": "+880", "flag": "https://flagcdn.com/w320/bd.png" },
    { "country": "Taiwan", "code": "+886", "flag": "https://flagcdn.com/w320/tw.png" },
    { "country": "Maldives", "code": "+960", "flag": "https://flagcdn.com/w320/mv.png" },
    { "country": "Lebanon", "code": "+961", "flag": "https://flagcdn.com/w320/lb.png" },
    { "country": "Jordan", "code": "+962", "flag": "https://flagcdn.com/w320/jo.png" },
    { "country": "Syria", "code": "+963", "flag": "https://flagcdn.com/w320/sy.png" },
    { "country": "Iraq", "code": "+964", "flag": "https://flagcdn.com/w320/iq.png" },
    { "country": "Kuwait", "code": "+965", "flag": "https://flagcdn.com/w320/kw.png" },
    { "country": "Saudi Arabia", "code": "+966", "flag": "https://flagcdn.com/w320/sa.png" },
    { "country": "Yemen", "code": "+967", "flag": "https://flagcdn.com/w320/ye.png" },
    { "country": "Oman", "code": "+968", "flag": "https://flagcdn.com/w320/om.png" },
    { "country": "Palestine", "code": "+970", "flag": "https://flagcdn.com/w320/ps.png" },
    { "country": "United Arab Emirates", "code": "+971", "flag": "https://flagcdn.com/w320/ae.png" },
    { "country": "Israel", "code": "+972", "flag": "https://flagcdn.com/w320/il.png" },
    { "country": "Bahrain", "code": "+973", "flag": "https://flagcdn.com/w320/bh.png" },
    { "country": "Qatar", "code": "+974", "flag": "https://flagcdn.com/w320/qa.png" },
    { "country": "Bhutan", "code": "+975", "flag": "https://flagcdn.com/w320/bt.png" },
    { "country": "Mongolia", "code": "+976", "flag": "https://flagcdn.com/w320/mn.png" },
    { "country": "Nepal", "code": "+977", "flag": "https://flagcdn.com/w320/np.png" },
    { "country": "Tajikistan", "code": "+992", "flag": "https://flagcdn.com/w320/tj.png" },
    { "country": "Turkmenistan", "code": "+993", "flag": "https://flagcdn.com/w320/tm.png" },
    { "country": "Azerbaijan", "code": "+994", "flag": "https://flagcdn.com/w320/az.png" },
    { "country": "Georgia", "code": "+995", "flag": "https://flagcdn.com/w320/ge.png" },
    { "country": "Kyrgyzstan", "code": "+996", "flag": "https://flagcdn.com/w320/kg.png" },
    { "country": "Uzbekistan", "code": "+998", "flag": "https://flagcdn.com/w320/uz.png" },
    { "country": "Antigua and Barbuda", "code": "+1268", "flag": "https://flagcdn.com/w320/ag.png" },
    { "country": "Bahamas", "code": "+1242", "flag": "https://flagcdn.com/w320/bs.png" },
    { "country": "Barbados", "code": "+1246", "flag": "https://flagcdn.com/w320/bb.png" },
    { "country": "Bermuda", "code": "+1441", "flag": "https://flagcdn.com/w320/bm.png" },
    { "country": "British Virgin Islands", "code": "+1284", "flag": "https://flagcdn.com/w320/vg.png" },
    { "country": "Cayman Islands", "code": "+1345", "flag": "https://flagcdn.com/w320/ky.png" },
    { "country": "Dominica", "code": "+1767", "flag": "https://flagcdn.com/w320/dm.png" },
    { "country": "Dominican Republic", "code": "+1809", "flag": "https://flagcdn.com/w320/do.png" },
    { "country": "Grenada", "code": "+1473", "flag": "https://flagcdn.com/w320/gd.png" },
    { "country": "Guam", "code": "+1671", "flag": "https://flagcdn.com/w320/gu.png" },
    { "country": "Jamaica", "code": "+1876", "flag": "https://flagcdn.com/w320/jm.png" },
    { "country": "Montserrat", "code": "+1664", "flag": "https://flagcdn.com/w320/ms.png" },
    { "country": "Northern Mariana Islands", "code": "+1670", "flag": "https://flagcdn.com/w320/mp.png" },
    { "country": "Puerto Rico", "code": "+1787", "flag": "https://flagcdn.com/w320/pr.png" },
    { "country": "Saint Kitts and Nevis", "code": "+1869", "flag": "https://flagcdn.com/w320/kn.png" },
    { "country": "Saint Lucia", "code": "+1758", "flag": "https://flagcdn.com/w320/lc.png" },
    { "country": "Saint Vincent and the Grenadines", "code": "+1784", "flag": "https://flagcdn.com/w320/vc.png" },
    { "country": "Trinidad and Tobago", "code": "+1868", "flag": "https://flagcdn.com/w320/tt.png" },
    { "country": "Turks and Caicos Islands", "code": "+1649", "flag": "https://flagcdn.com/w320/tc.png" },
    { "country": "US Virgin Islands", "code": "+1340", "flag": "https://flagcdn.com/w320/vi.png" }
]
